version: '3.8'
services:
  api:
    container_name: fluorine-commands-api
    build:
      context: ./
      target: production
    image: fluorine-commands-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - './:/src'